version: '3.8'

services:
  # Frontegg Entitlements Agent (Required for ReBAC)
  entitlements-agent:
    image: frontegg/entitlements-agent:latest
    container_name: frontegg-entitlements-agent
    ports:
      - "8181:8181"
    environment:
      - FRONTEGG_CLIENT_ID=${FRONTEGG_CLIENT_ID}
      - FRONTEGG_CLIENT_CREDENTIALS_OAUTH_CLIENT_ID=${FRONTEGG_API_TOKEN_CLIENT_ID}
      - FRONTEGG_CLIENT_CREDENTIALS_OAUTH_SECRET=${FRONTEGG_API_TOKEN_SECRET}
      - FRONTEGG_REGION=${FRONTEGG_REGION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health?bundles=frontegg"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Note: SQLite is file-based and doesn't require a Docker container
# The database.sqlite file will be created automatically in the backend directory